### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dskvr** [EOSIO/welcome#107]
Solution to #99

**Comment by bobgt** [comment]
@dskvr: Did we receive any updates from the legal?

**Comment by iamveritas** [comment]
after the license document is added verify/update all the links that point to license document (e.g. this page http://docsgen.a.qa.dev.b1ops.net.s3-website-us-west-2.amazonaws.com/welcome/latest/index has a license link, make sure it is correct).
