### ISSUE TITLE
Missing links in manuals directory

### ISSUE THREAD

**Issue by dskvr** [EOSIO/welcome#114]
- `demux-js` -  https://github.com/EOSIO/demux-js
- `history-tools` - https://eosio.github.io/history-tools

**Comment by bobgt** [comment]
> * `demux-js` -  https://github.com/EOSIO/demux-js
> * `history-tools` - https://eosio.github.io/history-tools

@dskvr: I understand demux is deprecated. Do we still need to include it?

**Comment by dixia** [comment]
fixed by #151
