### ISSUE TITLE
Naming rule and calculation of possibilities

### ISSUE THREAD

**Issue by b1aafulei** [EOSIO/welcome#157]
File: [docs/04_protocol/04_accounts_and_permissions.md](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/04_accounts_and_permissions.md)

The `2. Accounts` section claims that

> Each account is identified by a human readable name between 2 and 12 characters in length. The characters can include a-z, 1-5, and optional dots (.) except the first and last characters.

But it seems it is possible to create both a name of length one, like `a`, and a name that starts (but not ends) with dot, like `.a`.

```
$ cleos create account eosio a EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

executed transaction: f8a6bce3730e94f6821897b90afd00826802894cef7695a7dce9e27682a83d7f
200 bytes  649 us
#         eosio <= eosio::newaccount
{"creator":"eosio","name":"a","owner":{"threshold":1,"keys":
[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpsc...
```

```
$ cleos create account eosio .a EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

executed transaction: 38125f56699bfd1a83beeb2e6ca51abfe411292fc269821973eead054d3a1dd5
200 bytes  122 us
#         eosio <= eosio::newaccount 
{"creator":"eosio","name":".a","owner":{"threshold":1,"keys":
[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVps...
```

If it is possible to do this, then the calculation for the number of possibilities need to be changed as well.

**Comment by dixia** [comment]
It looks at least by @b1aafulei's example, if we revise the line:

"a human readable name between 2 and 12 characters in length." 

to 

"a human readable name between 1 and 12 characters in length."

It would be more accurate. Do you guys @iamveritas  @lparisc @b1aafulei agree or have more to add?

**Comment by bobgt** [comment]
Alternately, we can also say **a human readable name of minimum 1 and maximum 12 characters in length**.

**Comment by dixia** [comment]
@lparisc can you confirm the suggested change in this ticket ?

**Comment by lparisc** [comment]
I will update the formula.

**Comment by b1aafulei** [comment]
Hey, thanks for the update. Today I got a chance to take a look at the updated formula. I agree with the result, but there seems to be no need to apply the summation formula for the arithmetic series 

```
31^{1} \cdot \sum_{n=0}^{n=11} 32^{n}
```

which might have taken an unnecessary long way.

Let's we go back to the design of `eosio::name`. It maps a 64-bit unsigned integer to a human-readable name. Every 64-bit unsigned integer is a valid `eosio::name`, except for only one integer `0`.

For the account name, we can use only the first 60 bits. Every 60-bit unsigned integer is a valid account name, except for only one integer `0`.

Therefore, we directly get the result: each of the 60 bits can be either `0` or `1`, except for the only one case where all 60 bits are `0`. That is,

```
2 ^ 60 - 1
```

Of course, this is for this document owner's reference. Thank you.
