### ISSUE TITLE
Upgrading smart contract tutorial

### ISSUE THREAD

**Issue by dixia** [EOSIO/welcome#161]
There were some smart contract examples existing previously but it is no longer on the portal such as tik tac toe

**Comment by iamveritas** [comment]
previous version, needs to be updated
https://github.com/EOSIO/welcome/blob/readme-io-migrated-content/_readme.io/eosio-cpp-2019-11-15/v1.6/Tutorials/Creating%20a%20Tic-Tac-Toe%20Smart%20Contract.md

**Comment by dixia** [comment]
Thanks for the link!

**Comment by dixia** [comment]
This PL address this partial #195
