### ISSUE TITLE
"Public Key Persistence" seems not working correctly

### ISSUE THREAD

**Issue by zma** [EOSIO/welcome#186]
In 1.4 https://developers.eos.io/welcome/latest/getting-started/development-environment/create-development-wallet , I submit the "Development Public Key".

Then visit 1.6 https://developers.eos.io/welcome/latest/getting-started/development-environment/create-test-accounts , the `YOUR_PUBLIC_KEY` fields are not replaced with the public key.

I am using Chrome 81.0.4044.92 (Official Build) (64-bit) on Mac.

**Comment by dixia** [comment]
hi @zma thanks for the report. This does look a bug. I will check with developers

**Comment by dixia** [comment]
@zma it should be fixed by now. Could you confirm?

**Comment by zma** [comment]
@dixia thanks. It works as expected now as I just tested.

**Comment by dixia** [comment]
great to hear
