### ISSUE TITLE
Add EOSlime to community dev tools list

### ISSUE THREAD

**Issue by lparisc** [EOSIO/welcome#190]
EOSlime: https://github.com/LimeChain/eoslime

**Comment by bakasura980** [comment]
Hey guys, is there something miss I should add to the pull request for approval?

**Comment by bobgt** [comment]
> Hey guys, is there something miss I should add to the pull request for approval?

Thanks @bakasura980 for your submission. Your PR is merged!

**Comment by bakasura980** [comment]
Thank you!
