### ISSUE TITLE
ABI struct links seems outdated

### ISSUE THREAD

**Issue by zma** [EOSIO/welcome#191]
In https://developers.eos.io/welcome/latest/getting-started/smart-contract-development/understanding-ABI-files , the link of "here" from the part "If you would like to familiarize yourself with EOSIO's built-ins, they are defined here" seems not very accurate. I believe it should link to the `abi_serializer::configure_built_in_types()` function. I think it might be a tiny bug.

**Comment by dixia** [comment]
So that link should points to defined but in types. It should be this [link](https://github.com/EOSIO/eos/blob/b39b6bd3c74ff47fc53fa80aafa2c1941ba82879/libraries/chain/abi_serializer.cpp#L88) by the current version instead of that function.

But this is a broken link

**Comment by dixia** [comment]
I updated this link but a better solution need to be found
