### ISSUE TITLE
Title of Step 10 in 2.4 Data Persistency should be "... Ricardian Contract"

### ISSUE THREAD

**Issue by zma** [EOSIO/welcome#192]
In https://developers.eos.io/welcome/latest/getting-started/smart-contract-development/data-persistence/#step-12-compile-the-contract

> Step 10 Prepare the Ricardian **Clauses** [Optional]
> Contracts compiled without a Ricardian contract ...

The title seems contain a typo.

**Comment by dixia** [comment]
will fix in #194
