### ISSUE TITLE
[docs] Suggestion / Change Request: block id type and ref_block_prefix

### ISSUE THREAD

**Issue by zma** [EOSIO/welcome#196]
File: [docs/04_protocol/01_consensus_protocol.md](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/01_consensus_protocol.md)

In the page (the block schema table):

```
id | uint64_t | UUID of this block ID (a function of block header and block number); can be used to query block for validation/retrieval purposes
```

From definition, `block_id_type` is a sha256:

`./types.hpp:  using block_id_type    = fc::sha256;`

It seems there may be a small bug in the doc?

and 

```
ref_block_prefix	uint32_t	lower 32 bits of block ID; used to prevent replay attacks
```
`ref_block_prefix` is part of the transaction, not a part of the block schema.

**Comment by dixia** [comment]
want to review this? @lparisc

**Comment by zma** [comment]
The ref_block_prefix following the `id` seems not part of the block schema. Added here too.

**Comment by dixia** [comment]
Hi @zma, mind to directly create a PL for this?

**Comment by zma** [comment]
> Hi @zma, mind to directly create a PL for this?

No problem. I will try to fix this and send a PR.

**Comment by lparisc** [comment]
@zma yes the `id` type should be a `block_id_type` not `uint64_t` - please include this correction in your PR. Regarding `ref_block_prefix`, however, the block schema should reflect the view of the block object retrieved from the chain (for instance, a block returned by a block explorer), which might differ from the actual object stored in the chain. In this case, a block retrieved from the chain does include `block_num` and `ref_block_prefix` fields at the end of every block retrieved: https://github.com/EOSIO/eos/blob/master/plugins/chain_plugin/chain_plugin.cpp#L2077. Check for instance [block 25](https://testnet.eos.io/block/25) from testnet, which btw also contains the first list of producers.

**Comment by zma** [comment]
> @zma yes the `id` type should be a `block_id_type` not `uint64_t` - please include this correction in your PR.

Sure. Will do that.

> Regarding `ref_block_prefix`, however, the block schema should reflect the view of the block object retrieved from the chain (for instance, a block returned by a block explorer), which might differ from the actual object stored in the chain. In this case, a block retrieved from the chain does include `block_num` and `ref_block_prefix` fields at the end of every block retrieved: https://github.com/EOSIO/eos/blob/master/plugins/chain_plugin/chain_plugin.cpp#L2077. Check for instance [block 25](https://testnet.eos.io/block/25) from testnet, which btw also contains the first list of producers.

I see. Thanks for the explanation. Then it's logical to include it in the doc as the doc is for developers on EOSIO.

**Comment by zma** [comment]
@lparisc and @dixia, PR #203 created. Kindly check.

**Comment by zma** [comment]
@lparisc since the PR was merged, I am closing this issue here.
