### ISSUE TITLE
[docs] typo in 2.5: Secondary Indices

### ISSUE THREAD

**Issue by dimas1185** [EOSIO/welcome#210]
there few places 'index_by' is mentioned.
correct struct name is 'indexed_by' as in this code:

`typedef eosio::multi_index<"people"_n, person,
indexed_by<"byage"_n, const_mem_fun<person, uint64_t, &person::get_secondary_1>>> address_index;`

https://developers.eos.io/welcome/v2.0/getting-started/smart-contract-development/secondary-indices

**Comment by dixia** [comment]
hi @dimas1185 this has been fixed. could you double check?

**Comment by dimas1185** [comment]
looks good!
