### ISSUE TITLE
 2.1. Account Schema

### ISSUE THREAD

**Issue by bobgt** [EOSIO/welcome#214]
File: [docs/04_protocol/04_accounts_and_permissions.md](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/04_accounts_and_permissions.md)

In the **2.1. Account Schema** table, the description text for `privileged` account schema has a question mark. I am guessing it's a typo. 

If yes, fix the typo. If it is part of the description, ignore and close this issue.

**Comment by dixia** [comment]
I think it is a type, I don't think we need this question mark.

**Comment by dixia** [comment]
Could you confirm? @lparisc

**Comment by lparisc** [comment]
It was supposed to be a question mark since the type is `bool`. So if the answer to the question is *true* the account is privileged, *false* otherwise. To make it more clear, you could change the description as follows: "True, if privilege account, False otherwise".
