### ISSUE TITLE
API description is wrong

### ISSUE THREAD

**Issue by swang-b1** [EOSIO/welcome#228]
https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index#operation/abi_json_to_bin

**Comment by dixia** [comment]
Filed in the upstream repo: https://github.com/EOSIO/eos/issues/9162

**Comment by lparisc** [comment]
@dixia it's easier just to transfer the issue (bottom-right of page) instead of recreating a new issue and removing the old.
