### ISSUE TITLE
[docs] Updating the Sample Code for TicTacToe Tutorial

### ISSUE THREAD

**Issue by nuwanwre** [EOSIO/welcome#308]
Thanks for the tutorial!

However I noticed some minor typos that could lead to confusion.

In the tutorials for Single Node and Testnet, the code samples for `tictactoe.cpp` and `tictactoe.hpp` contain some typos.
The classname and the constructor can be changed to `tictactoe` from `TicTacToe` in `tictactoe.hpp`. This causes a compiler error on the cpp file. 

Also, on the cpp file, a couple of changes could be made  `IsValidCheck(...)` -> `isValidCheck(...)` and `GetWinner(...)` -> `getWinner(...)`

**Comment by lparisc** [comment]
Published
