### ISSUE TITLE
Getting Started vs Get Started

### ISSUE THREAD

**Issue by dskvr** [EOSIO/welcome#31]
A complaint was brought up that there's inconsistency between Getting Started and Get Started. Share thoughts below.

**Comment by dixia** [comment]
Any other opinions? We move this forward a bit

**Comment by iamveritas** [comment]
I think you give it too much value
https://textranch.com/277981/getting-started/or/get-started/

the difference is how the "get" verb is conjugated
if it makes sense from grammatical point of view to use the "Getting started" vs "Get started" in a phrase then it can be used; however, for a button/link/actionable "Get Started" is more appropriate than "Getting Started" from my point of view.

**Comment by dixia** [comment]
Let us settle with `Getting Started`. The importance is to be consistent and getting started is more commonly used

**Comment by iamveritas** [comment]
> Let us settle with `Getting Started`. The importance is to be consistent and getting started is more commonly used

according to what stats is `Getting Started` more commonly used?

**Comment by sunshineveg** [comment]
Get Started is a call to action, I agree it is the appropriate usage for a clickable button. It is not appropriate usage for the title of a guide, how-to, or tutorial.

In documentation, Getting Started typically refers to the process of beginning to use a product for the first time - It answers the question "where do I start?"

**Comment by iamveritas** [comment]
drawing conclusions of all feedback, I propose that the buttons/links/menu actions to be called "Get Started" and the title of the page where the button/link/menu action transfer the user to should be "Getting Started".

**Comment by sunshineveg** [comment]
👍

On Wed, Feb 26, 2020 at 9:17 AM ovi <notifications@github.com> wrote:

> drawing conclusions of all feedback, I propose that the buttons/links/menu
> actions to be called "Get Started" and the title of the page where the
> button/link/menu action transfer the user to should be "Getting Started".
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EOSIO_welcome_issues_31-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANVT4M65S5GC7WJRNOQX7YTREZ2YLA5CNFSM4KHFBYQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENAMR2Q-23issuecomment-2D591448298&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=O45V9_ZZZ4a2YVjXtHedEsg52XxYDH3KQ3jjvDLWYfQ&m=-0cEpBIXgX_USWpo-CObE19v86Des3g9L6Qe6bjDDMQ&s=ye4lpKjOQXewkRlgbK2gu5ELtUzrmQ0BV2rmEIEvH5Y&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVT4M332ZVJUSKO32Q2JVTREZ2YLANCNFSM4KHFBYQQ&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=O45V9_ZZZ4a2YVjXtHedEsg52XxYDH3KQ3jjvDLWYfQ&m=-0cEpBIXgX_USWpo-CObE19v86Des3g9L6Qe6bjDDMQ&s=Ww4rAtD6qOn_zoDVOXSQpD2mufwafhMFn1irX7uPJsU&e=>
> .
>


-- 

*Virginia Glass*
*Manager, Technical Writing*
virginia.glass@block.one

*The information contained in this email is confidential together with any
information contained in any attachments to this email. You should not
disclose, give or copy the information to anyone other than the person(s)
who are named or referenced above. The law may also protect the information
as a legally privileged document and/or as a copyright work. If you have
received this email and you are not the person named or referenced above,
please let the sender know and delete the email from your computer (and, if
applicable, your computer system(s) and server(s)). For information about
how we process personal data and monitor communications please see our
privacy policy <https://block.one/privacy-policy/> and for terms of use
please see our terms of use here. <https://block.one/terms-of-use/>*
