### ISSUE TITLE
[docs] Delayed status ambiguity in transaction receipt

### ISSUE THREAD

**Issue by b1bart** [EOSIO/welcome#321]
File: [docs/04_protocol/02_transactions_protocol.md](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/02_transactions_protocol.md)

refer to https://github.com/EOSIO/eos/issues/9454#issuecomment-694182838

The poster is confused due to the definition of `delayed` execution status which could imply that *any* transaction scheduled for future execution bears this status when it is scheduled.  This is *not* the case for deferred transactions issued by a contract.  We should clarify that this status is specifically for explicit user-created/signed transactions which have a delay to satisfy authorizations. 

If we already describe those transactions elsewhere in the documentation we can probably just link to that.

**Comment by lparisc** [comment]
I will make it more clear/explicit in the `status` field explainer from [3.6.1. Transaction Receipt](https://github.com/EOSIO/welcome/blob/master/docs/04_protocol/02_transactions_protocol.md#361-transaction-receipt), but this is mentioned in the next sections:

[3.6.2. Deferred Transactions](https://github.com/EOSIO/welcome/blob/master/docs/04_protocol/02_transactions_protocol.md#362-deferred-transactions)
"...there is no need to explicitly include their contents in the transaction receipt."

[3.6.3. Delayed User Transactions](https://github.com/EOSIO/welcome/blob/master/docs/04_protocol/02_transactions_protocol.md#363-delayed-user-transactions)
"...they bear a "delayed" status so their execution and validation can be postponed."
