### ISSUE TITLE
BP's not producing block after restart every server including genesis

### ISSUE THREAD

**Issue by shikhars371** [EOSIO/welcome#360]
Hello All.
Its my request to kindly please assist me in the following condition which im facing on my servers,
I been running EOS privately with my servers, some days before on 12 my genesis node got crashed due to chain-state-db-size-mb error and when my genesis node crashed all othe BP nodes were also crashed, before 12th everything was working fine all BP were producing block, but on 12 when genesis nodes was crashed , i started the geneisis node with tag —chain-state-db-size-mb = 70000 , then i started all my BP nodes and also started my 3 new nodes, these 3 new nodes took around 2 days to sync because the block number has increased to millions, now my problem is no BP's are producing blocks, ON genesis node it just keep on showing:

info  2020-11-18T03:22:23.243 net-1     net_plugin.cpp:3080           connection_monitor   ] p2p client connections: 24/25, peer connections: 0/0

and on BP nodes

info  2020-11-17T17:34:38.978 net-0     net_plugin.cpp:3080           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1

what can be the issue im really confused, before it was producing and after the restart BP's are not producing its wierd

**Comment by shikhars371** [comment]
thanks resolve with -e tag

**Comment by iamveritas** [comment]
hello @shikhars371 from the last message I get it you found a solution and we can close this issue? in any case this repository is not the right place to ask this question, I kindly advise you to post it in telegram there is a channel dedicated for EOS block producers there named "EOS Mainnet BPs"
