### ISSUE TITLE
Error: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by Joyia012** [EOSIO/welcome#374]
I am facing some error while runiing this command

`cleos create account eosio eosio.bpay EOS6wFEd5JHuUHWtaV12mxnm1v9udPsdrB7LUy1mVFc8iYJNdDMaL
`
It show'sthe output given below

```
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.

```
And when i run cleos get account eosio it shows different keys which are not in my wallet. Its a Developers key which is given in EOSIO Developers site.

**Comment by iamveritas** [comment]
am I correct to assume you are following the [`BIOS Boot Sequence`](https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequence) tutorial?

to solve that error make sure your keys are store in the local wallet like it is explained in [this step](https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequence#17-create-important-system-accounts).

**Comment by Joyia012** [comment]
yes, I am following the https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequencel

**Comment by Joyia012** [comment]
I have done again as you said but still I am facing the error

```
 cleos wallet keys
[
  "EOS6Amb73zYoN8cjLUKii1Dmt7nSUuugkC5sh8eLZmR4Ew6xSFZbi",
  "EOS6wFEd5JHuUHWtaV12mxnm1v9udPsdrB7LUy1mVFc8iYJNdDMaL"
]

```
`cleos create account eosio eosio.bpay EOS6Amb73zYoN8cjLUKii1Dmt7nSUuugkC5sh8eLZmR4Ew6xSFZbi
`
```
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.
[root@104-156-59-166 genesis]# cleos wallet private_keys -n w1

```
```
password: [[
    "EOS6Amb73zYoN8cjLUKii1Dmt7nSUuugkC5sh8eLZmR4Ew6xSFZbi",
    "5K6PcFhx1FKZvVhNaFxTww1XsqT7TDzYDD9SwWmJzxkYjqW8vq3"
  ],[
    "EOS6wFEd5JHuUHWtaV12mxnm1v9udPsdrB7LUy1mVFc8iYJNdDMaL",
    "5KA4Gm3kiym2FBDTxc2hSyR8Kg2fUz27EcuMpZu1wjgfYEeQfPv"
  ]
]
```
See it works it import the keys but I think the erroe is in this command, when i run this cleos get accounts eosio. it will show different owner keys as we have the key in the EOS Documentation. Can you tell me how to remove the active owner key

**Comment by iamveritas** [comment]
to change eosio account permissions you still need the private key for public key EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV added to the wallet.

**Comment by Blockchainer1** [comment]
@iamveritas I saw this link [Set Account](https://developers.eos.io/manuals/eos/latest/cleos/command-reference/set/set-account#options) but can't understand how to implement this. Can you please help me in that.

**Comment by iamveritas** [comment]
to add the missing key to your wallet run the following commands at your command shell prompt:

```sh
cleos wallet unlock
<enter your wallet key>

cleos wallet import
< paste the development key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 >

cleos wallet keys
< you should see next to your other keys the following public dev key which is set for your eosio account as well:
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV" >

cleos create account eosio eosio.bpay EOS6Amb73zYoN8cjLUKii1Dmt7nSUuugkC5sh8eLZmR4Ew6xSFZbi
< now this command should succeed >
```

**Comment by Blockchainer1** [comment]
It Works Thanks :+1:
