### ISSUE TITLE
Update the docs to run it on Ubuntu 20

### ISSUE THREAD

**Issue by marimeireles** [EOSIO/welcome#386]
Hello folks,
I currently have an Ubuntu 20 and made EOS work in here without compiling things from scratch. If you're interested I can update your docs with my solution :)
Cheers,

**Comment by iamveritas** [comment]
if you want to contribute you are welcome to open a PR; it will be reviewed and follow the process as for the other PRs.
the guidelines for community contributors are outlined here:
https://developers.eos.io/welcome/latest/welcome-to-eosio/community-contributions/index
