### ISSUE TITLE
[docs] Hello World guide cannot be accessed (404 error)

### ISSUE THREAD

**Issue by Mobterest** [EOSIO/welcome#418]
File: [docs/40_smart-contract-guides/index.md](https://github.com/EOSIO/welcome/blob/develop/docs/40_smart-contract-guides/index.md)

The https://developers.eos.io/welcome/latest/getting-started-guide/hello-world cannot be accessed. It displays 404: Page not Found

**Comment by lparisc** [comment]
This has been fixed. Thanks for letting us know.
