### ISSUE TITLE
[docs] BIOS Boot Sequence Tutorial - missing eosio.boot in master

### ISSUE THREAD

**Issue by liquidstudios** [EOSIO/welcome#424]
File: [docs/80_tutorials/10_bios-boot-sequence.md](https://github.com/EOSIO/welcome/blob/develop/docs/80_tutorials/10_bios-boot-sequence.md)

BIOS Boot Sequence Tutorial cannot be fully completed because the master-branch doesn't contain eos/contracts/contracts/eosio.boot/ anymore but the tutorial advises to clone the master. Starting from [build eosioboot system contract](https://developers.eos.io/welcome/v2.1/tutorials/bios-boot-sequence/#182-build-eosioboot-system-contract)

**Comment by iamveritas** [comment]
fixed by https://github.com/EOSIO/welcome/pull/425

**Comment by iamveritas** [comment]
> File: [docs/80_tutorials/10_bios-boot-sequence.md](https://github.com/EOSIO/welcome/blob/develop/docs/80_tutorials/10_bios-boot-sequence.md)
> 
> BIOS Boot Sequence Tutorial cannot be fully completed because the master-branch doesn't contain eos/contracts/contracts/eosio.boot/ anymore but the tutorial advises to clone the master. Starting from [build eosioboot system contract](https://developers.eos.io/welcome/v2.1/tutorials/bios-boot-sequence/#182-build-eosioboot-system-contract)

thank you for pointing it out; indeed the command line steps should contain a step which checks out the `release/2.1.x` branch; it has been addressed by https://github.com/EOSIO/welcome/pull/425 and it will be deployed in a couple of days.
