### ISSUE TITLE
Developer Guide Menu Click not as expected

### ISSUE THREAD

**Issue by stone89son** [EOSIO/welcome#429]
Bug Developer Guide Menu Click not as expected.
https://developers.eos.io/welcome/latest/getting-started-guide/index
![eosre](https://user-images.githubusercontent.com/6795515/117559947-76508880-b0c4-11eb-94c4-0901e06b841d.JPG)

**Comment by iamveritas** [comment]
@stone89son thank you for your feedback
can you please be more specific about what you believe it should be fixed, what it is not correctly shown in the menu?

**Comment by stone89son** [comment]
that day when I clicked on each menu in the blue area, but it did not click as I expected.
Example: If I click on "System Requirements" then it selected the menu "Install the EOSIO.CDT"
today I do not see that error.
![test____](https://user-images.githubusercontent.com/6795515/117745328-395fcf80-b245-11eb-8ba3-7f0e2701c609.PNG)
