### ISSUE TITLE
Page for "get involved" is missing

### ISSUE THREAD

**Issue by dskvr** [EOSIO/welcome#67]
- [ ] Write some content that makes contribution to EOSIO seem less daunting. The two forms of contribution at this time are:
  a. Contribute to source
  b. Contribute to documentation 
- [ ] Update `docs.json` with link to `get-involved` page.

**Comment by bobgt** [comment]
Get involved page is now available on the Developers portal:

https://developers.eos.io/welcome/latest/get-involved/index
