### ISSUE TITLE
License link is broken

### ISSUE THREAD

**Issue by iamveritas** [EOSIO/welcome#99]
go to page: http://docsgen.a.qa.dev.b1ops.net.s3-website-us-west-2.amazonaws.com/welcome/latest/index

click on License link on the right side panel
it goes to this link https://github.com/EOSIO/welcome/blob/master/LICENSE which results in a 404

**Comment by dixia** [comment]
Hi @iamveritas, was @dskvr answer good enough or we should take some actions?

**Comment by iamveritas** [comment]
there's a later issue which will create a license doc.
I have updated that issue to also verify all the links to license for correctness. 
we can close this issue now.

**Comment by dixia** [comment]
close this issue as #107 is tracking this
